[2024-08-20T10:10:38.049+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Vehicle_Data_scrape_Pipeline_3.scrape_post_links manual__2024-08-20T10:09:56.234460+00:00 [queued]>
[2024-08-20T10:10:38.055+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Vehicle_Data_scrape_Pipeline_3.scrape_post_links manual__2024-08-20T10:09:56.234460+00:00 [queued]>
[2024-08-20T10:10:38.055+0000] {taskinstance.py:2193} INFO - Starting attempt 2 of 4
[2024-08-20T10:10:38.065+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): scrape_post_links> on 2024-08-20 10:09:56.234460+00:00
[2024-08-20T10:10:38.070+0000] {standard_task_runner.py:60} INFO - Started process 1097 to run task
[2024-08-20T10:10:38.072+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Vehicle_Data_scrape_Pipeline_3', 'scrape_post_links', 'manual__2024-08-20T10:09:56.234460+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/vehicle_data_scraping_pipeline.py', '--cfg-path', '/tmp/tmpzzgwrz50']
[2024-08-20T10:10:38.073+0000] {standard_task_runner.py:88} INFO - Job 9: Subtask scrape_post_links
[2024-08-20T10:10:38.110+0000] {task_command.py:423} INFO - Running <TaskInstance: Vehicle_Data_scrape_Pipeline_3.scrape_post_links manual__2024-08-20T10:09:56.234460+00:00 [running]> on host 8369baedd275
[2024-08-20T10:10:38.258+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='sdeshan' AIRFLOW_CTX_DAG_ID='Vehicle_Data_scrape_Pipeline_3' AIRFLOW_CTX_TASK_ID='scrape_post_links' AIRFLOW_CTX_EXECUTION_DATE='2024-08-20T10:09:56.234460+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-20T10:09:56.234460+00:00'
[2024-08-20T10:10:43.797+0000] {logging_mixin.py:188} WARNING -   0%|          | 0/4 [00:00<?, ?it/s]
[2024-08-20T10:10:43.798+0000] {logging_mixin.py:188} WARNING - 100%|##########| 4/4 [00:00<00:00, 41120.63it/s]
[2024-08-20T10:10:52.247+0000] {logging_mixin.py:188} WARNING -   0%|          | 0/11 [00:00<?, ?it/s]
[2024-08-20T10:10:52.249+0000] {logging_mixin.py:188} WARNING - 100%|##########| 11/11 [00:00<00:00, 59996.55it/s]
[2024-08-20T10:10:58.752+0000] {logging_mixin.py:188} WARNING -   0%|          | 0/24 [00:00<?, ?it/s]
[2024-08-20T10:10:58.754+0000] {logging_mixin.py:188} WARNING - 100%|##########| 24/24 [00:00<00:00, 79828.15it/s]
[2024-08-20T10:11:01.440+0000] {logging_mixin.py:188} WARNING -   0%|          | 0/24 [00:00<?, ?it/s]
[2024-08-20T10:11:01.441+0000] {logging_mixin.py:188} WARNING - 100%|##########| 24/24 [00:00<00:00, 87685.80it/s]
[2024-08-20T10:11:02.875+0000] {logging_mixin.py:188} WARNING -   0%|          | 0/5 [00:00<?, ?it/s]
[2024-08-20T10:11:02.879+0000] {logging_mixin.py:188} WARNING - 100%|##########| 5/5 [00:00<00:00, 39945.75it/s]
[2024-08-20T10:11:06.531+0000] {logging_mixin.py:188} WARNING -   0%|          | 0/4 [00:00<?, ?it/s]
[2024-08-20T10:11:06.532+0000] {logging_mixin.py:188} WARNING - 100%|##########| 4/4 [00:00<00:00, 39850.87it/s]
[2024-08-20T10:11:13.782+0000] {logging_mixin.py:188} WARNING -   0%|          | 0/1 [00:00<?, ?it/s]
[2024-08-20T10:11:13.783+0000] {logging_mixin.py:188} WARNING - 100%|##########| 1/1 [00:00<00:00, 14364.05it/s]
[2024-08-20T10:11:17.883+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/components/vehicle/data_scraping_components/post_links_extraction.py", line 68, in scrape_links
    upload_table('ikman_vehicle_post_links')
  File "/opt/airflow/dags/components/utils/database_table_creation.py", line 29, in upload_table
    cur.execute(f"""
psycopg2.errors.InsufficientPrivilege: could not open file "/var/lib/postgresql/csv/ikman_vehicle_post_links.csv" for writing: Permission denied
HINT:  COPY TO instructs the PostgreSQL server process to write a file. You may want a client-side facility such as psql's \copy.

[2024-08-20T10:11:17.909+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=Vehicle_Data_scrape_Pipeline_3, task_id=scrape_post_links, execution_date=20240820T100956, start_date=20240820T101038, end_date=20240820T101117
[2024-08-20T10:11:17.920+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 9 for task scrape_post_links (could not open file "/var/lib/postgresql/csv/ikman_vehicle_post_links.csv" for writing: Permission denied
HINT:  COPY TO instructs the PostgreSQL server process to write a file. You may want a client-side facility such as psql's \copy.
; 1097)
[2024-08-20T10:11:17.930+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-08-20T10:11:17.945+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
