[2024-09-24T06:50:25.425+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Gold_training_Pipeline.scrape_time_series_data scheduled__2024-09-19T00:00:00+00:00 [queued]>
[2024-09-24T06:50:25.464+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Gold_training_Pipeline.scrape_time_series_data scheduled__2024-09-19T00:00:00+00:00 [queued]>
[2024-09-24T06:50:25.465+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 4
[2024-09-24T06:50:25.525+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): scrape_time_series_data> on 2024-09-19 00:00:00+00:00
[2024-09-24T06:50:25.571+0000] {standard_task_runner.py:60} INFO - Started process 328 to run task
[2024-09-24T06:50:25.630+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Gold_training_Pipeline', 'scrape_time_series_data', 'scheduled__2024-09-19T00:00:00+00:00', '--job-id', '155', '--raw', '--subdir', 'DAGS_FOLDER/gold_training_pipeline.py', '--cfg-path', '/tmp/tmphh420n21']
[2024-09-24T06:50:25.657+0000] {standard_task_runner.py:88} INFO - Job 155: Subtask scrape_time_series_data
[2024-09-24T06:50:27.859+0000] {task_command.py:423} INFO - Running <TaskInstance: Gold_training_Pipeline.scrape_time_series_data scheduled__2024-09-19T00:00:00+00:00 [running]> on host f2466956ab47
[2024-09-24T06:50:28.236+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='sdeshan' AIRFLOW_CTX_DAG_ID='Gold_training_Pipeline' AIRFLOW_CTX_TASK_ID='scrape_time_series_data' AIRFLOW_CTX_EXECUTION_DATE='2024-09-19T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-19T00:00:00+00:00'
[2024-09-24T06:50:28.243+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-09-24T06:50:28.307+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=Gold_training_Pipeline, task_id=scrape_time_series_data, execution_date=20240919T000000, start_date=20240924T065025, end_date=20240924T065028
[2024-09-24T06:50:28.326+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:207 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2024-09-24T06:50:28.358+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/email.py:154 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2024-09-24T06:50:28.359+0000] {email.py:270} INFO - Email alerting: attempt 1
[2024-09-24T06:50:30.227+0000] {email.py:281} INFO - Sent an alert email to ['deshanariyarathna@gmail.com']
[2024-09-24T06:50:31.189+0000] {taskinstance.py:1127} ERROR - Error when executing success_email callback
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1124, in _run_finished_callback
    callback(context)
  File "/opt/airflow/dags/components/utils/send_email.py", line 12, in success_email
    send_email(to = to_email, subject = subject, html_content = body)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 282, in send_mime_email
    smtp_conn.sendmail(e_from, e_to, mime_msg.as_string())
  File "/usr/local/lib/python3.8/smtplib.py", line 900, in sendmail
    (code, resp) = self.data(msg)
  File "/usr/local/lib/python3.8/smtplib.py", line 569, in data
    raise SMTPDataError(code, repl)
smtplib.SMTPDataError: (421, b'4.3.0 Temporary System Problem. Try again later (10). For more information,\n4.3.0 go to\n4.3.0  https://support.google.com/a/answer/3221692 d2e1a72fcca58-71afc834304sm615957b3a.10 - gsmtp')
[2024-09-24T06:50:31.263+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-09-24T06:50:31.286+0000] {taskinstance.py:3312} INFO - 1 downstream tasks scheduled from follow-on schedule check
